== Processos

=== 1) Descobrindo o número de processos em execução

1. Quantos processos estão sendo executados na máquina no momento? Use o comando `wc` para contá-los.
ifdef::gabarito[]
+
.................
# ps aux | sed -n '1!p' | wc -l
71
.................
endif::gabarito[]

2. Faça um _script_ que liste o número de processo que cada usuário está executando.
ifdef::gabarito[]
+
O _script shell_ abaixo mostra um exemplo de solução para o problema proposto:
+
[source,bash]
----
include::{srcdir}/sessao_3/pscount.sh[]
----
endif::gabarito[]

=== 2) Descobrindo o PID e o PPID de um processo

1. Quais os valores de `PID` e `PPID` do shell que você está utilizando no sistema?
ifdef::gabarito[]
+
.................
$ echo -e "PID: $$\nPPID: $PPID"
PID: 1016
PPID: 1015
.................
endif::gabarito[]

2. Faça um _script_ que liste todos os processos que foram iniciados pelo processo `init`. A lista não deve conter mais de uma ocorrência do mesmo processo.
ifdef::gabarito[]
+
O _script shell_ abaixo mostra um exemplo de solução para o problema proposto:
+
[source,bash]
----
include::{srcdir}/sessao_3/pinit_count.sh[]
----
endif::gabarito[]

=== 3) Estados dos processos

1. Qual o status mais frequente dos processos que estão sendo executados no sistema? Você saberia explicar por quê?
ifdef::gabarito[]
+
.................
$ ps aux | awk '{print $8}' | sort | uniq -c | sort -n | tac
     24 S
     23 S<
     16 Ss
      4 S+
      1 STAT
      1 Ssl
      1 Ss+
      1 SN
      1 R+
      1 D+
.................
+
O estado mais frequente é _sleep_, porque apenas um processo pode estar sendo executado pela CPU em um dado momento.
endif::gabarito[]

=== 4) Alternando a execução de processos

1. Execute o comando `$ sleep 1000` diretamente do terminal.
ifdef::gabarito[]
+
.................
$ sleep 1000
.................
endif::gabarito[]

2. Pare o processo e mantenha-o em memória.
ifdef::gabarito[]
+
Basta digitar a combinação de teclas `CTRL + Z`.
+
.................
$ sleep 1000
^Z
[1]+  Parado
.................
endif::gabarito[]

3. Liste os processos parados.
ifdef::gabarito[]
+
.................
$ jobs
[1]+  Parado                  sleep 1000
.................
endif::gabarito[]

4. Coloque-o em _background_.
ifdef::gabarito[]
+
.................
$ bg
[1]+ sleep 1000 &
$ jobs
[1]+  Executando              sleep 1000 &
.................
endif::gabarito[]

5. Verifique se o comando sleep 1000 está rodando.
ifdef::gabarito[]
+
.................
$ ps ax | egrep 'sleep 1000$'
 2178 pts/0    S      0:00 sleep 1000
.................
endif::gabarito[]

6. É possível cancelar a execução desse comando quando ele está rodando em _background_? Caso seja possível, faça-o.
ifdef::gabarito[]
+
.................
$ kill 2178
$ ps ax | egrep 'sleep 1000$'
[1]+  Terminado               sleep 1000
.................
endif::gabarito[]

=== 5) Identificando o RUID e o EUID de um processo

1. Logado como o usuário `aluno`, execute o comando `passwd` no seu terminal. Antes de mudar a senha, abra uma segunda console e autentique-se como `root`. Verifique o `RUID` e o `EUID` associados ao processo `passwd`. Esses valores são iguais ou diferentes? Você saberia explicar por quê? Por fim, cancele a execução do processo `passwd`.
ifdef::gabarito[]
+
Na primeira console, execute:
+
.................
$ passwd
Mudando senha para aluno.
Senha UNIX (atual):
.................
+
Antes de digitar a senha, abra uma segunda console como `root` e execute:
+
.................
# ps -eo user,ruser,comm | egrep '^USER | passwd$'
USER     RUSER    COMMAND
root     aluno    passwd

# which passwd
/usr/bin/passwd
# ls -lh /usr/bin/passwd
-rwsr-xr-x 1 root root 53K Mai 17  2017 /usr/bin/passwd
.................
+
Os valores são diferentes porque o binário `passwd` possui o bit _SUID_ ativado. O `RUID` (_real uid_) é do usuário que está executando o comando e o EUID (_effective uid_) é o do usuário `root`, que é o dono do arquivo.
endif::gabarito[]

=== 6) Definindo a prioridade de processos

1. Verifique as opções do comando `nice` e em seguida, execute o comando abaixo, verificando sua prioridade, utilizando o comando `ps`:
+
.................
# nice -n -15 sleep 1000 &
[1] 2289
.................
ifdef::gabarito[]
+
Basta executar o comando `# ps lax` e buscar o processo relevante, verificando o valor da quinta coluna. Em uma única linha e de forma mais específica, podemos fazer:
+
.................
# ps lax | egrep ' sleep 1000$' | awk '{print $5}'
2289 5
.................
endif::gabarito[]

2. Repita o comando do primeiro item, passando para o comando `nice` o parâmetro `-n -5`. Verifique como isso afeta a prioridade do processo. Ela aumentou, diminuiu ou permaneceu a mesma?
ifdef::gabarito[]
+
.................
# nice -n -5 sleep 1000 &
[2] 2312
# ps lax | egrep ' sleep 1000$' | awk '{print $3, $5}'
2289 5
2312 15
.................
+
A prioridade diminuiu, porque quanto maior o valor na coluna `PRI`, menor a prioridade do processo.
endif::gabarito[]

=== 7) Editando arquivos crontab para o agendamento de tarefas

Neste exercício, trabalharemos com o comando `crontab`, utilizado para editar os arquivos `cron` do agendador de tarefas do sistema.Esses arquivos serão verificados pelo _daemon_ `cron` periodicamente em busca de tarefas para serem executadas pelo sistema. Para entender o funcionamento do `crontab`, o primeiro passo é ler as páginas do manual relevantes.

[NOTE]
====
Para o comando `crontab` em si, consulte a seção 1 do manual:
====

.................
$ man 1 crontab
.................

[NOTE]
====
Para o formato de um arquivo de configuração `crontab`, consulte a seção 5:
====

.................
$ man 5 crontab
.................

1. Existe alguma entrada de `crontab` para o seu usuário?
ifdef::gabarito[]
+
.................
$ crontab -l
no crontab for aluno
.................
endif::gabarito[]

2. Que opção deve ser usada para editar o seu arquivo de `crontab`?
ifdef::gabarito[]
+
.................
$ crontab -e
no crontab for aluno - using an empty one

Select an editor.  To change later, run 'select-editor'.
  1. /bin/nano        <---- easiest
  2. /usr/bin/vim.basic
  3. /usr/bin/vim.tiny

Choose 1-3 [1]: 1
No modification made
.................
endif::gabarito[]

=== 8) Agendando uma tarefa no daemon cron

Neste exercício, será necessário enviar mensagens de correio eletrônico. Para isso, você deverá utilizar o comando `mail`; o instrutor pode fornecer as informações básicas sobre ele. Um exemplo do uso desse comando para enviar uma mensagem ao endereço `fulano@dominio` com o assunto _Mensagem de teste_ é:

.................
$ mail fulano@dominio -s "Mensagem de teste" < /dev/null
.................

1. Configure o `crontab` para que uma mensagem de correio eletrônico seja enviada automaticamente pelo sistema, sem interferência do administrador às 20:30 horas.
ifdef::gabarito[]
+
Utilize o comando `$ crontab -e` para editar o `crontab` e inserir a linha:
+
.................
30 20 * * * mail fulano@dominio -s "Mensagem de teste" < /dev/null
.................
endif::gabarito[]

2. Como verificar se a configuração foi feita corretamente?
ifdef::gabarito[]
+
.................
$ crontab -l | egrep -v '^#'
30 20 * * * mail fulano@dominio -s "Mensagem de teste" < /dev/null
.................
endif::gabarito[]

3. Qual o requisito fundamental para garantir que a ação programada será executada?
ifdef::gabarito[]
+
O daemon do `cron` deve estar em execução e a sintaxe do `crontab`, incluindo a linha de comando utilizada, deve estar correta.
endif::gabarito[]

4. Há como confirmar se a mensagem foi efetivamente enviada, sem consultar o destinatário?
ifdef::gabarito[]
+
Verifique no arquivo `/var/log/syslog` se a tarefa foi executada no horário correto com sucesso. Você deve ver uma entrada do tipo:
+
.................
/var/log/syslog:Aug  7 17:40:01 cliente CRON[2524]: (aluno) CMD (COMMAND)
.................
+
Dependendo da distribuição Linux em uso, as mensagens relativas ao `cron` podem estar em `/var/log/syslog`, `/var/log/cron.log`, `/var/log/daemon.log` ou outros arquivos. Verifique na documentação do fabricante/mantenedor.
endif::gabarito[]

5. Dê dois exemplos de utilização desse mecanismo para apoiar atividades do administrador de sistemas.
ifdef::gabarito[]
+
Podemos, por exemplo, utilizar o `cron` para agendamento de backups e limpeza de diretórios temporários.
endif::gabarito[]

6. Faça um script que liste os arquivos sem dono do sistema e envie a lista por e-mail ao usuário root.
ifdef::gabarito[]
+
O _script shell_ abaixo mostra um exemplo de solução para o problema proposto, com a característica adicional de guardar os logs enviados por e-mail em um diretório dentro do _home_ do `root`:
+
[source,bash]
----
include::{srcdir}/sessao_3/find_nouser.sh[]
----
endif::gabarito[]

7. Agende no crontab do usuário `root` o script do item 6, de modo que ele seja executado de segunda a sexta às 22:30 horas.
ifdef::gabarito[]
+
Logado como usuário `root`, digite o comando `# crontab -e` para editar o `crontab` e insira a linha a seguir:
+
.................
30 22 * * 1-5 /root/scripts/find_nouser.sh
.................
endif::gabarito[]

=== 9) Listando e removendo arquivos crontab

1. Liste o conteúdo do seu arquivo de `crontab` e, em seguida, remova-o. Quais as opções utilizadas para executar as ações demandadas?
ifdef::gabarito[]
+
.................
$ crontab -l | egrep -v '^#'
30 20 * * * mail fulano@dominio -s "Mensagem de teste" < /dev/null

$ crontab -r
$ crontab -l
no crontab for aluno
.................
endif::gabarito[]

=== 10) Entendendo o comando exec

1. Execute o comando `$ exec ls -l`. Explique o que aconteceu.
ifdef::gabarito[]
+
.................
# whoami
root
# exec ls -l /mnt/
total 0

$ whoami
aluno
.................
+
O shell corrente foi finalizado. Sempre que um comando é executado, um novo processo é criado. Já quando um comando é executado como argumento do comando `exec`, a imagem do shell corrente é substituída pela do processo invocado, e quando esse processo encerra sua execução já não há mais shell de retorno.
endif::gabarito[]
