version: "3"
services:
  web:
    # substitua username/repo:tag com suas informacoes de nome de usuario, repositorio e imagem
    image: username/repo:tag
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7080:80"
    networks:
      - webnet
networks:
  webnet:
