- name: Install nginx and deps
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: true
    install_recommends: no
  vars:
    packages:
    - nginx
    - php-fpm
    - php-mysql
  notify:
    - Start nginx
    - Start php-fpm

- name: Add seg10 config
  template:
    src: 'nginx_domain.j2'
    dest: '/etc/nginx/sites-available/{{ domain }}'
    owner: root
    group: root

- name: Disable default site configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable seg10 site config
  file:
    src: '/etc/nginx/sites-available/{{ domain }}'
    dest: '/etc/nginx/sites-enabled/{{ domain }}'
    state: link

- name: Copy web root
  synchronize:
    src: '{{ domain }}'
    dest: '/var/www'
    recursive: yes
    
- name: Web Root Permissions
  file:
   dest: '/var/www/{{ domain }}'
   mode: u=rwX,g=rX,o=rX
   state: directory
   owner: www-data
   group: www-data
   recurse: yes
  notify:
    - Reload nginx
