---
- name: Start nginx
  service:
    name: nginx
    state: started

- name: Start php-fpm
  service:
    name: php7.0-fpm
    state: started

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
