ifdef::oneof[]
////
= SEG12 - Semana 1 - Sessão 12
:Author: Francisco_Marcelo,_Marcelo_Karam_e_Felipe_Scarel
:Author Initials: FM & MK & FS
////
:doctype: article
:source-highlighter: rouge
:listing-caption: Listing
:pdf-page-size: A4
:revdate: 06-08-2018
:imagesdir: ../img
:srcdir: ../src
:icons: font
include::../../locale/attributes.adoc[]
endif::oneof[]

== Correio Eletrônico -- POP/IMAP

[WARNING]
====
As atividades 1, 2 e 3 desta sessão serão realizadas na máquina virtual _Server_Linux_. A atividade 4 será realizada na máquina _Win7-padrao_.
====

Iremos continuar a configuração da sessão anterior, instalando e configurando o MDA (_Mail Delivery Agent_) Courier.

=== 1) Configuração de entrega *_Maildir_*

No momento, o Postfix está configurado para entregar mensagens no estilo `mbox`, em que todas as mensagens ficam em um único arquivo no diretório _home_ do usuário. A modalidade de entrega `Maildir`, mais moderna, é preferível porque coloca cada mensagem dentro de um arquivo próprio, e as indexa permitindo controle de duplicidade, tempos de expiração e facilita procedimentos de busca. Além disso, o formato `Maildir` é mais performático que o `mbox`.

Crie, dentro da pasta de cada usuário existente no servidor, um diretório de nome `Maildir` com as seguintes sub-pastas: `new`, `cur`, `tmp`, `.Drafts`, `.Spam` e `.Trash` (observe o caractere "." na frente das últimas três pastas, indicando que são ocultas). Ajuste a permissão do diretório `Maildir` para `700`. A seguir, faça com que todos os usuários criados futuramente já tenham essa estrutura de diretórios criada em suas pastas _home_ automaticamente.

Depois, altere o estilo de entrega do Postfix de `mbox` para `Maildir`. Finalmente, envie uma mensagem para um usuário e teste se sua configuração surtiu efeito.

ifdef::gabarito[]
1. Para os usuários preexistentes, é necessário criar um diretório de nome `Maildir` com as pastas mencionadas pela atividade. Por exemplo, para o usuário `aluno`:
+
.................
# mkdir -p /home/aluno/Maildir/{cur,new,tmp,.Drafts,.Spam,.Trash}
# chown -R aluno.aluno /home/aluno/Maildir
# chmod 700 /home/aluno/Maildir
.................

2. Para fazer com que todos os usuários futuros já possuam a pasta `Maildir` e seus subdiretórios criados de forma automática no _home_, basta:
+
.................
# mkdir -p /etc/skel/Maildir/{cur,new,tmp,.Drafts,.Spam,.Trash}
# chmod 700 /etc/skel/Maildir
.................

3. Altere os parâmetros `home_mailbox` e `mailbox_command` do Postfix no arquivo `/etc/postfix/main.cf`, como se segue:
+
.................
# grep '^home_mailbox\|^mailbox_command' /etc/postfix/main.cf
home_mailbox = Maildir/
mailbox_command =
.................

4. Reinicie o Postfix:
+
.................
# systemctl restart postfix.service
.................

5. Envie um email para um usuário qualquer, digamos, o usuário `aluno`, usando o comando `mail`. Verifique nos logs do servidor SMTP o estilo da entrega:
+
.................
# echo 'Teste Maildir' | mail -s 'Teste' aluno@empresa.com.br

# tail -n4 /var/log/mail.log
Aug 12 21:54:00 email postfix/pickup[1587]: 78FA3A02AF: uid=0 from=<root@email.empresa.com.br>
Aug 12 21:54:00 email postfix/cleanup[1593]: 78FA3A02AF: message-id=<20180813005400.78FA3A02AF@email.empresa.com.br>
Aug 12 21:54:00 email postfix/qmgr[1588]: 78FA3A02AF: from=<root@email.empresa.com.br>, size=363, nrcpt=1 (queue active)
Aug 12 21:54:00 email postfix/local[1595]: 78FA3A02AF: to=<aluno@empresa.com.br>, relay=local, delay=0.01, delays=0.01/0/0/0, dsn=2.0.0, status=sent (delivered to maildir)
Aug 12 21:54:00 email postfix/qmgr[1588]: 78FA3A02AF: removed
.................

6. Verifique se a mensagem foi enviada corretamente para o diretório `Maildir` do usuário:
+
.................
# ls -R /home/aluno/Maildir/
/home/aluno/Maildir/:
cur  new  tmp

/home/aluno/Maildir/cur:

/home/aluno/Maildir/new:
1534121640.V801I605d1M501046.email

/home/aluno/Maildir/tmp:
.................
endif::gabarito[]

=== 2) Configuração do MDA Courier POP/IMAP

Os protocolos _Post Office Protocol_ (POP) e _Internet Message Access Protocol_ (IMAP) são utilizados pelos clientes de email (MUAs) para recuperar mensagens armazenadas no servidor de e-mail. Nesta atividade iremos configurar os servidores POP e IMAP, e testá-los usando o comando `telnet`.

Instale o Courier-POP e Courier-IMAP, pacotes `courier-imap-ssl`, `courier-pop-ssl`, `libsasl2-modules-ldap` e `gamin`. Passe a opção `--no-install-recommends` para o `apt-get` para que não sejam instalados alguns pacotes adicionais desnecessários à configuração que será feita. Ao ser perguntado se deseja "Criar diretórios para administração via web", responda negativamente.

Teste a conexão com os servidores POP e IMAP. Em caso de sucesso, autentique-se em ambos usando o comando `telnet`.

ifdef::gabarito[]
1. Primeiro, vamos instalar os pacotes solicitados:
+
.................
# apt-get install --no-install-recommends courier-imap-ssl courier-pop-ssl libsasl2-modules-ldap gamin
.................

2. Tente a conexão com o servidor POP. Em caso de sucesso, faça login como usuário `aluno` usando os comandos `USER` e `PASS`.
+
.................
# telnet localhost 110
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Aug 12 22:10:20 email pop3d: Connection, ip=[::1]
+OK Hello there.

USER aluno
+OK Password required.

PASS rnpesr
+OK logged in.
.................

3. Excelente! Vamos listar as mensagens usando o comando `LIST`. A seguir, exibir uma delas usando o comando `RETR`:
+
.................
Aug 12 22:10:25 email pop3d: LOGIN, user=aluno, ip=[::1], port=[38447]

LIST
+OK POP3 clients that break here, they violate STD53.
1 478
2 478
.

RETR 1
+OK 478 octets follow.
Return-Path: <root@email.empresa.com.br>
X-Original-To: aluno@empresa.com.br
Delivered-To: aluno@empresa.com.br
Received: by email.empresa.com.br (Postfix, from userid 0)
        id 78FA3A02AF; Sun, 12 Aug 2018 21:54:00 -0300 (-03)
Subject: Teste
To: <aluno@empresa.com.br>
X-Mailer: mail (GNU Mailutils 2.99.98)
Message-Id: <20180813005400.78FA3A02AF@email.empresa.com.br>
Date: Sun, 12 Aug 2018 21:54:00 -0300 (-03)
From: root@email.empresa.com.br (root)

Teste Maildir
.

QUIT
Aug 12 22:10:40 email pop3d: LOGOUT, user=aluno, ip=[::1], port=[38447], top=0, retr=465, rcvd=20, sent=607, time=15
+OK Bye-bye.
Connection closed by foreign host.
.................

4. Finalmente, vamos testar a conexão com o servidor IMAP. Apenas o procedimento de login e listagem de pastas é suficiente:
+
.................
# telnet localhost 143
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Aug 12 22:16:26 email imapd: Connection, ip=[::1]
* OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] Courier-IMAP ready. Copyright 1998-2011 Double Precision, Inc.  See COPYING for distribution information.

01 LOGIN aluno rnpesr
01 OK LOGIN Ok.
Aug 12 22:16:33 email imapd: LOGIN, user=aluno, ip=[::1], port=[50201], protocol=IMAP

. LIST "" "*"
* LIST (\Marked \HasNoChildren) "." "INBOX"
. OK LIST completed
.................
endif::gabarito[]

=== 3) Configuração de autenticação do POP/IMAP em LDAP

Altere as configurações do Cyrus-SASL para permitir autenticação a partir do diretório LDAP, em lugar do PAM. Você deve alterar os arquivos `/etc/default/saslauthd` e `/etc/postfix/sasl/smtpd.conf`. Além disso, será necessário criar um novo arquivo, `/etc/saslauthd.conf`, para especificar a base de pesquisa e filtros de busca na base LDAP.

Teste o funcionamento da configuração usando o comando `testsaslauthd`. Lembre-se que o Postfix está operando em `chroot`, e por conseguinte a localização do _socket_ do `saslauthd` deve ser informada manualmente.

[TIP]
====
Em caso de dúvidas, consulte http://www.postfix.org/SASL_README.html . Tenha especial atenção à configuração do _plugin_ `ldapdb`.
====

ifdef::gabarito[]
1. Primeiro, edite o arquivo `/etc/default/saslauthd` e altere o mecanismo de autenticação de `pam` para `ldap`:
+
.................
# cat /etc/default/saslauthd | grep '^MECHANISMS='
MECHANISMS="ldap"
.................

2. A seguir, edite o arquivo `/etc/postfix/sasl/smtpd.conf` para o Cyrus SASL utilizar o _plugin_ `ldapdb` em procedimentos de autenticação. Informe também a URL do diretório LDAP, usuário administrativo e senha:
+
[source,bash]
----
include::{srcdir}/s12/etc_postfix_sasl_smtpd.conf[]
----

3. Crie o arquivo novo `/etc/saslauthd.conf`. Nele, indique qual é o _search base_ de pesquisa no diretório LDAP, bem como o filtro de pesquisa:
+
[source,bash]
----
include::{srcdir}/s12/etc_saslauthd.conf[]
----

4. Reinicie os serviços `postfix` e `saslauthd`:
+
.................
# systemctl restart postfix.service
# systemctl restart saslauthd.service
.................

5. Teste o funcionamento da configuração com o comando `testsaslauthd`. Como o Postfix está em `chroot` no diretório `/var/spool/postfix`, temos que passar o caminho completo até o _socket_ com a opção `-f`. Vamos testar tanto com usuário local quanto com um usuário existente apenas no diretório LDAP:
+
.................
# testsaslauthd -u aluno -p rnpesr -f /var/spool/postfix/var/run/saslauthd/mux
0: OK "Success."

# testsaslauthd -u esr -p rnpesr -f /var/spool/postfix/var/run/saslauthd/mux
0: OK "Success."
.................
endif::gabarito[]

=== 4) Utilização de clientes POP/IMAP

Os programas clientes de e-mail (MUA) utilizam-se dos protocolos POP ou IMAP para recuperar mensagens no servidor de e-mail. Nesta atividade iremos configurar um cliente para o recebimento de mensagens usando esses protocolos.

1. Instale o cliente de e-mail _Mozilla Thunderbird_ na máquina _Win7-padrao_. Inicie o programa e crie uma nova conta de e-mail para o usuário `aluno`. Na tela inicial, informe:
+
.Opções para criação de conta de e-mail existente
[options="header",width="70%"]
|===
| Parâmetro | Valor
| Seu nome | aluno
| Endereço de e-mail | aluno@empresa.com.br
| Senha | rnpesr
|===

2. Agora, clique em "Continuar". O _Thunderbird_ irá tentar buscar configuração automática dos servidores, sem sucesso. Clique então em "Config. manual", e informe:
+
.Configurações avançadas para criação de e-mail
[options="header"]
|===
| Tipo | Protocolo | Nome do servidor | Porta | SSL | Autenticação
| Recebimento | IMAP | email.empresa.com.br | 143 | Nenhuma | Senha normal
| Envio | SMTP | email.empresa.com.br | 25 | STARTTLS | Senha normal
|===

3. Na parte de baixo, em "Nome de usuário", troque o valor padrão `aluno@empresa.com.br` para `aluno` apenas. Garanta que ambos os campos "Recebimento" e "Envio" estão corretos. Finalmente, clique em "Concluído".

4. O _Thunderbird_ irá avisar que o recebimento de e-mails (via IMAP) não está usando criptografia. Marque a caixa "Eu entendo os riscos" e depois clique em "Concluído".

5. Terminado esse passo, crie uma nova conta de e-mail, com as mesmas configurações explicadas acima, para um outro usuário do servidor.

6. Finalmente, teste o envio e recebimento de e-mails entre os dois usuários e verifique que o serviço está funcionando como esperado.
